### ISSUE TITLE
sanitize error: IndexError: list index out of range

### ISSUE THREAD

**Issue by maxlath** [firstlook/pdf-redact-tools#15]
running `pdf-redact-tools --sanitize an-untrusted.pdf` I got the following error:

```
Converting PDF to PNGs
Flattening PNGs
Traceback (most recent call last):
  File "/usr/bin/pdf-redact-tools", line 178, in <module>
    main()
  File "/usr/bin/pdf-redact-tools", line 170, in main
    if pdfrt.explode():
  File "/usr/bin/pdf-redact-tools", line 83, in explode
    filename_template = os.path.join(self.pages_dirname, filenames[0].replace('-0.png', '-{}.png'))
IndexError: list index out of range
```
It's a 5 Mo file, could that be too large for this operation? Any other clue on what could be the issue?

thanks in advance!

**Comment by ariccio** [comment]
It looks a bit more like `filenames` is an empty list, thus there's no valid index. It's filled with the list of files in a directory... it must have somehow been filled with an empty directory?

**Comment by bogomya** [comment]
I have the same issue. Ubuntu 14.04

**Comment by doctorcolossus** [comment]
same issue here - pdf-redact-tools 0.1.2 on Arch Linux
